export const ProductMock = [
  {
    name: "Produto 1",
    description: "Descrição do produto 1",
    urlImage: "https://picsum.photos/384/227?random=1",
    price: 10.99,
    visible: true,
  },
  {
    name: "Produto 2",
    description: "Descrição do produto 2",
    urlImage: "https://picsum.photos/384/227?random=2",
    price: 12.5,
    visible: true,
  },
  {
    name: "Produto 3",
    description: "Descrição do produto 3",
    urlImage: "https://picsum.photos/384/227?random=3",
    price: 8.75,
    visible: false,
  },
  {
    name: "Produto 4",
    description: "Descrição do produto 4",
    urlImage: "https://picsum.photos/384/227?random=4",
    price: 15.0,
    visible: true,
  },
  {
    name: "Produto 5",
    description: "Descrição do produto 5",
    urlImage: "https://picsum.photos/384/227?random=5",
    price: 9.99,
    visible: false,
  },
  {
    name: "Produto 6",
    description: "Descrição do produto 6",
    urlImage: "https://picsum.photos/384/227?random=6",
    price: 20.0,
    visible: true,
  },
  {
    name: "Produto 7",
    description: "Descrição do produto 7",
    urlImage: "https://picsum.photos/384/227?random=7",
    price: 11.25,
    visible: true,
  },
  {
    name: "Produto 8",
    description: "Descrição do produto 8",
    urlImage: "https://picsum.photos/384/227?random=8",
    price: 13.4,
    visible: false,
  },
  {
    name: "Produto 9",
    description: "Descrição do produto 9",
    urlImage: "https://picsum.photos/384/227?random=9",
    price: 7.8,
    visible: true,
  },
  {
    name: "Produto 10",
    description: "Descrição do produto 10",
    urlImage: "https://picsum.photos/384/227?random=10",
    price: 18.99,
    visible: true,
  },
  {
    name: "Produto 11",
    description: "Descrição do produto 11",
    urlImage: "https://picsum.photos/384/227?random=11",
    price: 14.5,
    visible: false,
  },
  {
    name: "Produto 12",
    description: "Descrição do produto 12",
    urlImage: "https://picsum.photos/384/227?random=12",
    price: 22.0,
    visible: true,
  },
  {
    name: "Produto 13",
    description: "Descrição do produto 13",
    urlImage: "https://picsum.photos/384/227?random=13",
    price: 16.75,
    visible: true,
  },
  {
    name: "Produto 14",
    description: "Descrição do produto 14",
    urlImage: "https://picsum.photos/384/227?random=14",
    price: 19.99,
    visible: false,
  },
  {
    name: "Produto 15",
    description: "Descrição do produto 15",
    urlImage: "https://picsum.photos/384/227?random=15",
    price: 9.5,
    visible: true,
  },
  {
    name: "Produto 16",
    description: "Descrição do produto 16",
    urlImage: "https://picsum.photos/384/227?random=16",
    price: 12.75,
    visible: true,
  },
  {
    name: "Produto 17",
    description: "Descrição do produto 17",
    urlImage: "https://picsum.photos/384/227?random=17",
    price: 21.0,
    visible: false,
  },
  {
    name: "Produto 18",
    description: "Descrição do produto 18",
    urlImage: "https://picsum.photos/384/227?random=18",
    price: 17.25,
    visible: true,
  },
  {
    name: "Produto 19",
    description: "Descrição do produto 19",
    urlImage: "https://picsum.photos/384/227?random=19",
    price: 23.5,
    visible: true,
  },
  {
    name: "Produto 20",
    description: "Descrição do produto 20",
    urlImage: "https://picsum.photos/384/227?random=20",
    price: 8.99,
    visible: false,
  },
  {
    name: "Produto 21",
    description: "Descrição do produto 21",
    urlImage: "https://picsum.photos/384/227?random=21",
    price: 10.5,
    visible: true,
  },
  {
    name: "Produto 22",
    description: "Descrição do produto 22",
    urlImage: "https://picsum.photos/384/227?random=22",
    price: 14.25,
    visible: true,
  },
  {
    name: "Produto 23",
    description: "Descrição do produto 23",
    urlImage: "https://picsum.photos/384/227?random=23",
    price: 19.75,
    visible: false,
  },
  {
    name: "Produto 24",
    description: "Descrição do produto 24",
    urlImage: "https://picsum.photos/384/227?random=24",
    price: 11.99,
    visible: true,
  },
  {
    name: "Produto 25",
    description: "Descrição do produto 25",
    urlImage: "https://picsum.photos/384/227?random=25",
    price: 13.8,
    visible: true,
  },
  {
    name: "Produto 26",
    description: "Descrição do produto 26",
    urlImage: "https://picsum.photos/384/227?random=26",
    price: 15.25,
    visible: false,
  },
  {
    name: "Produto 27",
    description: "Descrição do produto 27",
    urlImage: "https://picsum.photos/384/227?random=27",
    price: 20.5,
    visible: true,
  },
  {
    name: "Produto 28",
    description: "Descrição do produto 28",
    urlImage: "https://picsum.photos/384/227?random=28",
    price: 18.25,
    visible: true,
  },
  {
    name: "Produto 29",
    description: "Descrição do produto 29",
    urlImage: "https://picsum.photos/384/227?random=29",
    price: 9.75,
    visible: false,
  },
  {
    name: "Produto 30",
    description: "Descrição do produto 30",
    urlImage: "https://picsum.photos/384/227?random=30",
    price: 22.99,
    visible: true,
  },
  {
    name: "Produto 31",
    description: "Descrição do produto 31",
    urlImage: "https://picsum.photos/384/227?random=31",
    price: 16.4,
    visible: true,
  },
  {
    name: "Produto 32",
    description: "Descrição do produto 32",
    urlImage: "https://picsum.photos/384/227?random=32",
    price: 12.99,
    visible: false,
  },
  {
    name: "Produto 33",
    description: "Descrição do produto 33",
    urlImage: "https://picsum.photos/384/227?random=33",
    price: 24.5,
    visible: true,
  },
  {
    name: "Produto 34",
    description: "Descrição do produto 34",
    urlImage: "https://picsum.photos/384/227?random=34",
    price: 17.99,
    visible: true,
  },
  {
    name: "Produto 35",
    description: "Descrição do produto 35",
    urlImage: "https://picsum.photos/384/227?random=35",
    price: 21.75,
    visible: false,
  },
];
